export const creatives = [
    {
        name: "Gean Paulo",
        email: "hello@geanpaulo.com",
        skills: ["Frontend", "UI/UX", "Brand", "Graphics"],
        location: "Cainta, PH",
        experience: 5,
        bio: "Crafting high-performance web experiences through a blend of strategic design...",
        longBio: "With over 5 years of experience in the Philippine tech scene, I specialize in building bridges between complex backend logic and intuitive user interfaces. I've helped startups scale from zero to one by focusing on clean code and pixel-perfect design systems.",
        image: "images/gean.jpg",
        featuredWork: [
            { title: "Portfolio 2026", url: "https://geanpaulo.com/" },
            { title: "Always Ascending", url: "https://alwaysascending.store/" },
            { title: "Zen New Tab", url: "https://chromewebstore.google.com/detail/chhlgdhacpabpphphdhjicnpbpklpdbk?utm_source=item-share-cb" },
            { title: "Finetouch Maintenance", url: "https://finetouchmaintenance.com/" },
            { title: "In the Dog House Texas", url: "https://www.inthedoghousetx.com/" },
            { title: "Paramo Construction", url: "https://paramoconstructioninc.com/" },
            { title: "Currency Converter", url: "https://fxmirror.netlify.app/" },
            { title: "PayPal Fees Calculator", url: "https://ppfees.netlify.app/" }
        ],
        links: { website: "https://geanpaulo.com/", github: "https://github.com/geanpaulo19" },
        expiryDate: "2100-02-16" 
    },
    {
        name: "Julius Natividad",
        email: "julius@gmail.com",
        skills: ["Motion", "Graphics"],
        location: "Tuguegarao, PH",
        experience: 5,
        bio: "Creative strategist transforming brand visions into high-impact graphic identities and cinematic video content.",
        image: "images/julius.jpg",
        links: { facebook: "https://www.facebook.com/julius.blanza.natividad" },
    },
    {
        name: "Nicko Lamanilao",
        email: "franckolamanilao@gmail.com",
        skills: ["Brand", "Graphics", "Motion"],
        location: "Davao, PH",
        experience: 7,
        bio: "Crafting bold visuals and engaging videos that elevate brands.",
        image: "images/nicko.png",
        links: { portfolio: "https://franckolamanilao.my.canva.site/nicko-lamanilao-portfolio", facebook: "https://www.facebook.com/francko2021", instagram: "https://instagram.com/francko101", linkedin: "https://www.linkedin.com/in/frances-nicko-lamanilao-216ba1285",  },
    },
    {
        name: "Dana Praise Guerrero",
        email: "danapraiseguerrero@gmail.com",
        skills: ["Brand", "Graphics"],
        location: "Remote",
        experience: 3,
        bio: "Freelance Graphic Designer helping NGOs and start-ups expand their audience reach.",
        image: "images/dana.png",
        featuredWork: [
            { title: "Evergreen Labs Inc. | Visual Design", url: "https://www.behance.net/gallery/206121353/Evergreen-Labs-Inc-Visual-Design" },
            { title: "BSM Global | Content Creation, Branding", url: "https://www.behance.net/gallery/194585395/BSM-Global-Content-Creation-Branding" },
            { title: "Ad Creatives | Static", url: "https://www.behance.net/gallery/225782391/Ad-Creatives-Static" },
            { title: "Dodolove | E-commerce Design", url: "https://www.behance.net/gallery/204413189/Dodolove-E-commerce-Design" },
            { title: "Case Study | Lootgod", url: "https://www.behance.net/gallery/204714453/Case-Study-Lootgod" }
        ],
        links: { portfolio: "https://www.behance.net/danapraise", linkedin: "https://www.linkedin.com/in/danapraiseguerrero", behance: "https://behance.net/danapraise" },
    },
        {
        name: "Jeffrey Celestino",
        email: "jcelestino688@gmail.com",
        skills: ["Brand", "Graphics", "Frontend"],
        location: "Puerto Princesa, PH",
        experience: 5,
        bio: "As the owner of JEVM Graphics Design, this professional uses over five years of experience to create logos and marketing materials that help brands stand out. They turn creative ideas into clean, high-quality visuals that make a real impact.",
        image: "images/jeffrey.png",
        links: { portfolio: "https://jeffreycelestino.carrd.co", facebook: "https://www.facebook.com/jeffrey.celestino.55/", linkedin: "https://www.linkedin.com/in/jeffrey-celestino/", behance: "https://www.behance.net/jevmgraphicsdesign" },
    }
];
